# Generated by Django 4.1 on 2022-09-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=40, verbose_name='Correo')),
                ('documento', models.IntegerField(verbose_name='N° de documento')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y hora')),
                ('servicio', models.CharField(max_length=100, null=True, verbose_name='Servicio')),
            ],
        ),
    ]
