# Generated by Django 4.1 on 2022-09-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='hora',
            field=models.CharField(default=1, max_length=10, verbose_name='Horas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citas',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
